### ISSUE TITLE
Misc review from reddit.

### ISSUE THREAD

**Issue by Carreau** [TechPenguineer/chemispy#2]
Don't sys exit 1, it will kill the python process, raise and exception:

https://github.com/TechPenguineer/chemispy/blob/d3c35cec0cf3d595ad0ac35e0c340b1db6bd88df/chemispy/utils/atomic_number_query.py#L129

```
atomic_query_range = range(1,len(atomic_number_query.elements)+1)
if atomic_number not in atomic_query_range:
```

is the same as `if not 1 < atomic_number < atomic_number_query.elements +1:`

And the whole function can just be:

```
return atomic_number_query.elements[atomic_number-1]
```

It will just raise an error if it's not there.

```
class atomic_number_query:
    elements=[
              "Hydrogen",
              "Helium",
...
```

This is not java, you don't need classes everywhere. Just 
```
elements=[
              "Hydrogen",
              "Helium",
             ...
```

Is fine.

Same for https://github.com/TechPenguineer/chemispy/blob/d3c35cec0cf3d595ad0ac35e0c340b1db6bd88df/chemispy/elements/hydrogen.py and all element.

You likely want an Element base class and have each element be an instance.

You Like even want [a dataclass](https://docs.python.org/3/library/dataclasses.html)

Don't publish the `chemispy.egg-info`, 
and look into flake8 and black for code style.
For testing look into pytest.

You also likely want to see /r/learnpython on reddit 

Good luck

**Comment by TechPenguineer** [comment]
Thank you! The changes have been implemented!
